#!/bin/sh
set -ue

function install_files() {
  dotdir=$(pwd)

  ln -snf $dotdir/.config $HOME
  ln -snf $dotdir/.zshrc $HOME
}

install_files

git config --global commit.template ~/.config/commit_template.txt
git config --global init.defaultBranch main

sudo pacman -S --needed --noconfirm $(cat ./packages/dev.txt)
