#!/bin/sh
set -ue

function install_files() {
  dotdir=$(pwd)
  home=$HOME
  mkdir -p $home

  files=$(find .config -type f)
  for file in $files; do
    dir=$(dirname $file)
    mkdir -pv $home/$dir
    ln -svnf $dotdir/$file $home/$file
  done

  ln -svnf $dotdir/.zshrc $home
  ln -svnf $dotdir/imgs/wallpaper.png $home

  wget -O .config/waybar/mediaplayer.py https://raw.githubusercontent.com/Alexays/Waybar/refs/heads/master/resources/custom_modules/mediaplayer.py
}

function install_packages() {
  if command -v pacman >/dev/null 2>&1; then
    if command -v sudo >/dev/null 2>&1; then
      sudo pacman -Sy --needed --noconfirm $(cat ./packages/dev.txt)
    else
      pacman -Sy --needed --noconfirm $(cat ./packages/dev.txt)
    fi
  elif command -v apt-get >/dev/null 2>&1; then
    sudo apt-get install -y $(cat ./packages/dev-ubuntu.txt)
  fi
}

function setup_git_config() {
  if command -v git >/dev/null 2>&1; then
    git config --global user.name Yuta
    git config --global user.email jp.yuta0131@gmail.com
    git config --global commit.template ~/.config/commit_template.txt
    git config --global init.defaultBranch main
    git config --global ghq.root '~/dev'
  fi
}

install_packages
install_files
setup_git_config

# curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
# fisher install jethrokuan/z
