Section "InputClass"
  Identifier "keyboard"
  MatchIsKeyboard "on"

  Option "XkbLayout" "jp"
  Option "XkbOptions" "ctrl:nocaps,compose:ralt"
EndSection

Section "InputClass"
  Identifier "touchpad"
  MatchIsTouchpad "on"
  Driver "libinput"

  Option "NaturalScrolling" "true"
  Option "Tapping" "false"
  Option "DisableWhileTyping" "false"
EndSection
