bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind \\ split-window -h
bind - split-window -v

bind -T copy-mode-vi v send -X begin-selection

setw -g mode-keys vi
setw -g mouse on

set default-terminal tmux-256color
set -a terminal-overrides $TERM:RGB

# Status Line
set -g status-interval 1
set -g status-position top

set -g status-bg "#2a2e3b"
set -g status-fg "#000000"

set -g status-left-length 20
set -g status-right-length 20

set -g status-left "#[bg=colour3] Session: #S  #[default,fg=colour3]#[defalut] "
set -g status-right "#[fg=colour3]#[default,bg=colour3] #T "

set -g window-status-format "#[fg=colour0]#[default,bg=colour0] #I:#W #[default,fg=colour0]"
set -g window-status-current-format "#[fg=colour2]#[default,bg=colour2] #I:#W #[default,fg=colour2]"
