[style]
font_family = "Hack Nerd Font"
bold = true

[modules]
left = ["workspace"]
center = ["window"]
right = ["tray", "battery", "volume", "clock"]

[workspace]
persistent_workspaces = [1, 2, 3, 4, 5]
