#!/bin/bash

curl -LO --output-dir ~/.config/alacritty https://github.com/catppuccin/alacritty/raw/main/catppuccin-macchiato.toml
curl -LO --output-dir ~/.config/rofi https://github.com/catppuccin/rofi/raw/main/themes/catppuccin-macchiato.rasi
curl -LO --output-dir ~/.config/rofi https://github.com/catppuccin/rofi/raw/main/catppuccin-default.rasi
