[env]
TERM = "alacritty"

[terminal]
shell = "/usr/bin/fish"

[font]
size = 12
offset = { x = 1, y = 1 }
normal = { family = "Hack Nerd Font", style="Regular" }
bold = { family = "Hack Nerd Font", style="Bold" }
italic = { family = "Hack Nerd Font", style="Italic" }
bold_italic = { family = "Hack Nerd Font", style="Bold Italic" }

[window]
padding = { x = 4, y = 4 }
opacity = 0.95

[colors.primary]
background = "#0f121a"
foreground = "#eeeeee"

[colors.normal]
black = "#afb0b6"
red = "#d48686"
green = "#86d486"
yellow = "#d4d486"
blue = "#86add4"
magenta = "#ad86d4"
cyan = "#86d4d4"
white = "#eeeeee"

[colors.bright]
black = "#afb0b6"
red = "#d48686"
green = "#86d486"
yellow = "#d4d486"
blue = "#86add4"
magenta = "#ad86d4"
cyan = "#86d4d4"
white = "#eeeeee"

[colors.selection]
text = "CellForeground"
background = "#3f4353"
