name: CI
on:
  push:
    branches:
      - main

jobs:
  arch:
    name: Arch Linux
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dotfiles
        run: ./install
